import marker10ptsRarity         from '../../../../assets/images/marker-10pts-rarity.png';
import marker10ptsFlashCaptured  from '../../../../assets/images/marker-10pts-flash-captured.png';
import marker10ptsFlashUncaptured from '../../../../assets/images/marker-10pts-flash-uncaptured.png';
import marker10ptsGrey           from '../../../../assets/images/marker-10pts-grey.png';

import marker20ptsRarity         from '../../../../assets/images/marker-20pts-rarity.png';
import marker20ptsFlashCaptured  from '../../../../assets/images/marker-20pts-flash-captured.png';
import marker20ptsFlashUncaptured from '../../../../assets/images/marker-20pts-flash-uncaptured.png';
import marker20ptsGrey           from '../../../../assets/images/marker-20pts-grey.png';

import marker30ptsRarity         from '../../../../assets/images/marker-30pts-rarity.png';
import marker30ptsFlashCaptured  from '../../../../assets/images/marker-30pts-flash-captured.png';
import marker30ptsFlashUncaptured from '../../../../assets/images/marker-30pts-flash-uncaptured.png';
import marker30ptsGrey           from '../../../../assets/images/marker-30pts-grey.png';

import marker40ptsRarity         from '../../../../assets/images/marker-40pts-rarity.png';
import marker40ptsFlashCaptured  from '../../../../assets/images/marker-40pts-flash-captured.png';
import marker40ptsFlashUncaptured from '../../../../assets/images/marker-40pts-flash-uncaptured.png';
import marker40ptsGrey           from '../../../../assets/images/marker-40pts-grey.png';

import marker50ptsRarity         from '../../../../assets/images/marker-50pts-rarity.png';
import marker50ptsFlashCaptured  from '../../../../assets/images/marker-50pts-flash-captured.png';
import marker50ptsFlashUncaptured from '../../../../assets/images/marker-50pts-flash-uncaptured.png';
import marker50ptsGrey           from '../../../../assets/images/marker-50pts-grey.png';

import marker100ptsRarity         from '../../../../assets/images/marker-100pts-rarity.png';
import marker100ptsFlashCaptured  from '../../../../assets/images/marker-100pts-flash-captured.png';
import marker100ptsFlashUncaptured from '../../../../assets/images/marker-100pts-flash-uncaptured.png';
import marker100ptsGrey           from '../../../../assets/images/marker-100pts-grey.png';

// Golden "highlighted" variants — shown when an invader is picked for a multi-stop
// itinerary. One per tier so each invader keeps its own silhouette. Generated by
// frontend/scripts/gen-highlight-markers.py (hue-shift of the uncaptured sprites).
import marker10ptsHighlight  from '../../../../assets/images/marker-10pts-highlight.png';
import marker20ptsHighlight  from '../../../../assets/images/marker-20pts-highlight.png';
import marker30ptsHighlight  from '../../../../assets/images/marker-30pts-highlight.png';
import marker40ptsHighlight  from '../../../../assets/images/marker-40pts-highlight.png';
import marker50ptsHighlight  from '../../../../assets/images/marker-50pts-highlight.png';
import marker100ptsHighlight from '../../../../assets/images/marker-100pts-highlight.png';

import type { SymbolLayerStyle, Expression } from '@maplibre/maplibre-react-native';
import type { ImageSourcePropType } from 'react-native';
import { useMemo } from 'react';
import { useMarkerCustomizationStore } from '@/features/settings';

export const BUNDLED_MARKER_IMAGES = {
  'marker-10pts-rarity':           marker10ptsRarity,
  'marker-10pts-flash-captured':   marker10ptsFlashCaptured,
  'marker-10pts-flash-uncaptured': marker10ptsFlashUncaptured,
  'marker-10pts-grey':             marker10ptsGrey,

  'marker-20pts-rarity':           marker20ptsRarity,
  'marker-20pts-flash-captured':   marker20ptsFlashCaptured,
  'marker-20pts-flash-uncaptured': marker20ptsFlashUncaptured,
  'marker-20pts-grey':             marker20ptsGrey,

  'marker-30pts-rarity':           marker30ptsRarity,
  'marker-30pts-flash-captured':   marker30ptsFlashCaptured,
  'marker-30pts-flash-uncaptured': marker30ptsFlashUncaptured,
  'marker-30pts-grey':             marker30ptsGrey,

  'marker-40pts-rarity':           marker40ptsRarity,
  'marker-40pts-flash-captured':   marker40ptsFlashCaptured,
  'marker-40pts-flash-uncaptured': marker40ptsFlashUncaptured,
  'marker-40pts-grey':             marker40ptsGrey,

  'marker-50pts-rarity':           marker50ptsRarity,
  'marker-50pts-flash-captured':   marker50ptsFlashCaptured,
  'marker-50pts-flash-uncaptured': marker50ptsFlashUncaptured,
  'marker-50pts-grey':             marker50ptsGrey,

  'marker-100pts-rarity':           marker100ptsRarity,
  'marker-100pts-flash-captured':   marker100ptsFlashCaptured,
  'marker-100pts-flash-uncaptured': marker100ptsFlashUncaptured,
  'marker-100pts-grey':             marker100ptsGrey,

  'marker-10pts-highlight':  marker10ptsHighlight,
  'marker-20pts-highlight':  marker20ptsHighlight,
  'marker-30pts-highlight':  marker30ptsHighlight,
  'marker-40pts-highlight':  marker40ptsHighlight,
  'marker-50pts-highlight':  marker50ptsHighlight,
  'marker-100pts-highlight': marker100ptsHighlight,
};

// Merges the bundled default sprites with any user-generated marker PNGs
// (@/features/settings/marker-customization-store) — custom entries override
// bundled ones key-for-key, so uncustomized states keep shipping visuals.
export function useMarkerImages(): Record<string, ImageSourcePropType | number> {
  const customIconUris = useMarkerCustomizationStore((s) => s.customIconUris);
  return useMemo(() => {
    if (!customIconUris) return BUNDLED_MARKER_IMAGES;
    const merged: Record<string, ImageSourcePropType | number> = { ...BUNDLED_MARKER_IMAGES };
    for (const [key, uri] of Object.entries(customIconUris)) merged[key] = { uri };
    return merged;
  }, [customIconUris]);
}

// MapLibre's native <Images> only ever registers a given key once and
// ignores later value updates for it (confirmed in both the Android and iOS
// implementations of @maplibre/maplibre-react-native) — so after a
// re-customization the merged map from useMarkerImages() above is useless to
// an already-mounted map unless the whole component remounts. WebMap.native.tsx
// keys <Images> on this value to force that remount whenever it changes.
export function useMarkerImagesVersion(): number {
  return useMarkerCustomizationStore((s) => s.generationVersion);
}

export function useMarkerLayerStyle(): SymbolLayerStyle {
  const opacity = useMarkerCustomizationStore((s) => s.opacity);
  return useMemo(() => ({
    iconImage: ["get", "iconKey"] as Expression,
    iconSize: ["get", "iconSize"] as Expression,
    // The user's opacity setting scales *every* marker, including the dimmed
    // pending/grey ones, so "Marker opacity" affects the whole map (grey mode
    // included). At the default opacity of 1 this is identical to the old fixed
    // 0.45 / 0.8 / 1.0 values.
    iconOpacity: ["case",
      ["==", ["get", "pending"], 1], 0.45 * opacity,
      ["==", ["get", "grey"], 1],    0.8 * opacity,
      opacity,
    ] as Expression,
    iconAllowOverlap: true,
    iconIgnorePlacement: true,
  }), [opacity]);
}

export const MARKER_LAYER_FILTER = ["!", ["has", "point_count"]] as const;
